apiVersion: v1
kind: ConfigMap
metadata:
  name: aura-config
  namespace: aura
data:
  SPRING_PROFILES_ACTIVE: "prod"
  REDIS_HOST: "aura-redis"
  POSTGRES_HOST: "aura-postgres"
  DB_USER: "aura"
  VECTOR_DB_URL: "http://aura-vector-db:8000"
