server:
  port: 8080

spring:
  application:
    name: aura-api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: aura-agent-core
            uri: http://aura-agent-core:8083
            predicates:
              - Path=/api/agents/**
            filters:
              - StripPrefix=1
          - id: aura-user-service
            uri: http://aura-user-service:8082
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=1
          - id: aura-auth-service
            uri: http://aura-auth-service:8081
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
